// @ts-check
// See https://docusaurus.io/docs/api/docusaurus-config for all options.

const {themes: prismThemes} = require("prism-react-renderer");

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: "Kafka Flow",
  tagline: "Reliable processing of Kafka Journal events",
  favicon: "img/favicon.ico",
  // Old site used a middle dot in <title> ("Overview · Kafka Flow").
  titleDelimiter: "·",

  // Production URL and base path. Served at
  // https://evolution-gaming.github.io/kafka-flow/
  url: "https://evolution-gaming.github.io",
  baseUrl: "/kafka-flow/",

  // GitHub pages deployment config.
  organizationName: "evolution-gaming",
  projectName: "kafka-flow",

  onBrokenLinks: "throw",

  // Enable Mermaid diagrams in fenced ```mermaid code blocks.
  markdown: {
    mermaid: true,
    hooks: {
      onBrokenMarkdownLinks: "warn",
    },
  },
  themes: ["@docusaurus/theme-mermaid"],

  presets: [
    [
      "classic",
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          // Consume the markdown produced by `sbt docs/mdoc`.
          path: "../kafka-flow-docs/target/mdoc",
          routeBasePath: "docs",
          sidebarPath: require.resolve("./sidebars.js"),
          // No editUrl: docs are generated by `sbt docs/mdoc`, so an edit link
          // would point at the generated output rather than the real source.
        },
        // The blog was unused template boilerplate; disabled.
        blog: false,
        theme: {
          customCss: require.resolve("./src/css/custom.css"),
        },
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      // Social-card image (matches the old site's ogImage).
      image: "img/undraw_online.svg",
      // Dark mode is disabled for now: the old site was light-only, and the
      // dark theme still needs tuning (e.g. the primary-on-navbar color).
      // Re-enable by removing disableSwitch once the dark palette is tweaked.
      colorMode: {
        defaultMode: "light",
        disableSwitch: true,
        respectPrefersColorScheme: false,
      },
      navbar: {
        // Brand-purple navbar, matching the old Docusaurus 1 site.
        style: "primary",
        title: "Kafka Flow",
        logo: {
          alt: "Kafka Flow",
          src: "img/favicon.ico",
        },
        items: [
          {type: "doc", docId: "overview", position: "left", label: "Overview"},
          {type: "doc", docId: "setup", position: "left", label: "Setup"},
          {to: "/help", label: "Help", position: "left"},
        ],
      },
      footer: {
        style: "dark",
        logo: {
          alt: "Kafka Flow",
          src: "img/favicon.ico",
          width: 60,
          height: 52,
        },
        links: [
          {
            title: "Docs",
            items: [
              {label: "Overview", to: "/docs/overview"},
              {label: "Setup", to: "/docs/setup"},
              {
                label: "Sources",
                href: "https://github.com/evolution-gaming/kafka-flow",
              },
            ],
          },
          {
            title: "Community",
            items: [
              {label: "Twitter", href: "https://twitter.com/evoneering"},
            ],
          },
          {
            title: "More",
            items: [
              {
                label: "GitHub",
                href: "https://github.com/evolution-gaming/kafka-flow",
              },
            ],
          },
        ],
        copyright: `Copyright © ${new Date().getFullYear()} Evolution Gaming`,
      },
      prism: {
        theme: prismThemes.github,
        darkTheme: prismThemes.dracula,
        // `java` must precede `scala`: the Scala grammar extends Java.
        additionalLanguages: ["java", "scala"],
      },
    }),
};

module.exports = config;
