name: Dependency graph

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  submit:
    uses: evolution-gaming/scala-github-actions/.github/workflows/dependency-graph.yml@61f111a4472fde7b63e5921ac8a238f22d1bb028 # v7.0.1
    with:
      modules_ignore: >-
        docs_2.13
        docs_3
        kafka-flow-core-it-tests_2.13
        kafka-flow-core-it-tests_3
        kafka-flow-persistence-kafka-it-tests_2.13
        kafka-flow-persistence-kafka-it-tests_3
        kafka-flow-persistence-cassandra-it-tests_2.13
        kafka-flow-persistence-cassandra-it-tests_3