name: Update Dependency Graph
on:
  push:
    branches:
      - master
jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: 'sbt'

      - name: setup SBT
        uses: sbt/setup-sbt@v1

      - uses: scalacenter/sbt-dependency-submission@v2
        with:
          modules-ignore: >
            docs_2.13
            kafka-flow-core-it-tests_2.13
            kafka-flow-persistence-kafka-it-tests_2.13
            kafka-flow-persistence-cassandra-it-tests_2.13
          configs-ignore: test integration-test scala-tool scala-doc-tool
permissions:
  contents: write
