name: Dependency graph

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  submit:
    uses: evolution-gaming/scala-github-actions/.github/workflows/dependency-graph.yml@999c04ccae0d79a8a0c12ed7d71136762b2ae8c1 # v7.1.0
    with:
      modules_ignore: >-
        docs_2.13
        docs_3
        kafka-flow-core-it-tests_2.13
        kafka-flow-core-it-tests_3
        kafka-flow-persistence-kafka-it-tests_2.13
        kafka-flow-persistence-kafka-it-tests_3
        kafka-flow-persistence-cassandra-it-tests_2.13
        kafka-flow-persistence-cassandra-it-tests_3